Revert "Merge branch 'dev' of git://github.com/falcosecurity/falco into dev"
This reverts commit 7c2d8d847f539512ef3d9ffc382720ca70eae202, reversing
changes made to ccbaa0ff28e332773e5493cdfe375a321b2080ee.

diff --git a/docker/tester/root/usr/bin/entrypoint b/docker/tester/root/usr/bin/entrypoint
--- a/docker/tester/root/usr/bin/entrypoint
+++ b/docker/tester/root/usr/bin/entrypoint
@@ -24,11 +24,7 @@ case "$CMD" in
         exit 1
     fi
     if [ -z "$FALCO_VERSION" ]; then
-        echo "Automatically figuring out Falco version."
-        FALCO_VERSION=$($BUILD_DIR/$BUILD_TYPE/userspace/falco/falco --version | cut -d' ' -f3 | tr -d '\r')
-    fi
-    if [ -z "$FALCO_VERSION" ]; then
-        echo "Falco version cannot be guessed, please provide it with the FALCO_VERSION environment variable." >&2
+        echo "Missing Falco version." >&2
         exit 1
     fi
     PACKAGE="$BUILD_DIR/$BUILD_TYPE/falco-$FALCO_VERSION-x86_64.deb"
@@ -49,7 +45,7 @@ case "$CMD" in
     fi
     echo "Running regression tests ..."
     cd $SOURCE_DIR/falco/test
-    ./run_regression_tests.sh $BUILD_DIR/$BUILD_TYPE
+    bash run_regression_tests.sh $BUILD_DIR/$BUILD_TYPE
     docker rmi "$DOCKER_IMAGE_NAME" || true
     ;;
 "bash")
